__author__ = 'Robbie'

search_placeholders = [
    "why was the guy who created the libyan flag so lazy....",
    "people getting attacked by squirrels....",
    "dream with squirrels attacking....",
    "why are red and grey squirrels feuding....",
    "anger management for midget wrestlers....",
    "how can kenny die so many times....",
    "what do woodpeckers want for breakfast....",
    "did hitler grow his mustache like that on purpose?....",
    "is jesus the greatest magician of all time....",
    "how long should i put my baby in the oven for....",
    "is the government monitoring my searches....",
    "what is so mysterious about closets....",
    "why isn't 11 pronounced onety one....",
    "why is my goldfish turning black....",
    "don't you hate it when a sentence doesn't end the way you octopus....",
    "what do i do if a ginger person bites me....",
    "how come when i talk to girls on facebook they don't answer me back....",
    "amish online dating....",
    "google is better....",
    "what are jean claude van damme's legs made of....",
    "what would a chair look like if your knees bent the other way....",
    "is it safe to eat human meat?....",
    "how to raise your iq by eating smart children....",
    "why are there school....",
    "if i ate myself would i get twice as big or would i disappear completely....",
    "i can haz search ingin....",
    "why do all these old bands keep copying glee songs....",
    "can jesus microwave a burrito....",
    "am i a vegetarian if i eat vegetables with my meat....",
    "chuck norris can delete the recycle bin....",
    "chuck norris can slam a revolving door....",
    "are rhinos just fat unicorns that don't moisturise?...."
]
